rg2:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  
  
  gripper_joint_position:
    type: effort_controllers/JointPositionController
    joint: rg2_gripper_joint
    pid: {p: 5, i: 0.0, d: 0.0}