services:

  rviz:
    image: husarion/ur5e:melodic
    container_name: rviz
    restart: on-failure
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: rosrun rviz rviz -d /ros_ws/src/ur5e_bringup/config/rviz_config.rviz