services:

  ur-driver:
    build: ./..
    container_name: ur-drive
    restart: on-failure
    network_mode: host
    ipc: host
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
      - ROS_MASTER_URI=http://10.15.20.2:11311
    volumes:
      - ./../ur5e_moveit_config:/ros_ws/src/ur5e_moveit_config
    command: roslaunch moveit_setup_assistant setup_assistant.launch



# ur-drive            | N[ WARN] [1666626200.194143240]: No realtime capabilities found. Consider using a realtime system for better performance
# ur-drive            | [ WARN] [1666626200.263002580]: Joint state with name: "front_left_wheel_joint" was received but not found in URDF
# ur-drive            | [ WARN] [1666626200.681568391]: Skipping virtual joint 'virtual_joint' because its child frame 'base_link_inertia' does not match the URDF frame 'base_link'
# ur-drive            | [ERROR] [1666626200.782476041]: The kinematics plugin (manipulator) failed to load. Error: According to the loaded plugin descriptions the class trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin lma_kinematics_plugin/LMAKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin
# ur-drive            | [ERROR] [1666626200.782555612]: Kinematics solver could not be instantiated for joint group manipulator.
# ur-drive            | No protocol specified
# ur-drive            | freeglut failed to open display ':0'
# ur-drive            | [ INFO] [1666626200.679028954]: Loading robot model 'ur5e_robot'...
# ur-drive            | [ INFO] [1666626200.681590428]: No root/virtual joint specified in SRDF. Assuming fixed joint
# ur-drive            | [ INFO] [1666626200.871949252]: Publishing maintained planning scene on 'monitored_planning_scene'
# ur-drive            | [ INFO] [1666626200.881333100]: MoveGroup debug mode is OFF
# ur-drive            | Starting planning scene monitors...
# ur-drive            | [ INFO] [1666626200.881383032]: Starting planning scene monitor
# ur-drive            | [ INFO] [1666626200.892732484]: Listening to '/planning_scene'
# ur-drive            | [ INFO] [1666626200.892805203]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
# ur-drive            | [ INFO] [1666626200.901619706]: Listening to '/collision_object'
# ur-drive            | [ INFO] [1666626200.911080031]: Listening to '/planning_scene_world' for planning scene world geometry
# ur-drive            | [move_group-7] process has died [pid 100, exit code 1, cmd /opt/ros/melodic/lib/moveit_ros_move_group/move_group __name:=move_group __log:=/root/.ros/log/e6a30240-53aa-11ed-afee-0b9d6f89f287/move_group-7.log].
# ur-drive            | log file: /root/.ros/log/e6a30240-53aa-11ed-afee-0b9d6f89f287/move_group-7*.log
# ur-drive            | [ WARN] [1666626201.623538179]: No realtime capabilities found. Consider using a realtime system for better performance
# rviz                | [ WARN] [1666626201.772801065]: Skipping virtual joint 'virtual_joint' because its child frame 'base_link_inertia' does not match the URDF frame 'base_link'
# rviz                | [ERROR] [1666626201.845228276]: The kinematics plugin (manipulator) failed to load. Error: According to the loaded plugin descriptions the class trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin lma_kinematics_plugin/LMAKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin
# rviz                | [ERROR] [1666626201.845263575]: Kinematics solver could not be instantiated for joint group manipulator.
# ur-drive            | [ WARN] [1666626202.741929159]: No realtime capabilities found. Consider using a realtime system for better performance
# ur-drive            | [ WARN] [1666626210.310996581]: Joint state with name: "front_left_wheel_joint" was received but not found in URDF
# ur-drive            | [ WARN] [1666626220.360531231]: Joint state with name: "front_left_wheel_joint" was received but not found in URDF
# ur-drive            | [ WARN] [1666626230.415479223]: Joint state with name: "front_left_wheel_joint" was received but not found in URDF
# rviz                | [ERROR] [1666626237.310682019]: Unable to connect to move_group action server 'move_group' within allotted time (30s)
# ur-drive            | [ WARN] [1666626240.461616943]: Joint state with name: "front_left_wheel_joint" was received but not found in URDF
# ur-drive            | [ WARN] [1666626250.468819914]: Joint state with name: "front_left_wheel_joint" was received but not found in URDF 