services:

  ur-moveit-menager:
    image: husarion/ur5e:melodic
    container_name: ur-moveit-menager
    restart: on-failure
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - ./../ur5e_moveit_config:/ros_ws/src/ur5e_moveit_config
    command: roslaunch moveit_setup_assistant setup_assistant.launch