services:
  velodyne:
    # image: husarion/velodyne:noetic
    build: ./
    container_name: velodyne
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: >
      roslaunch velodyne_pointcloud VLP16_points.launch
        device_ip:=10.15.20.10
        frame_id:=velodyne
        port:=2368
