services:

  ur-driver:
    # image: husarion/ur5e:melodic
    build: ./../
    container_name: ur-drive
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    volumes:
      - ./../ur5e_moveit_config:/ros_ws/src/ur5e_moveit_config
      - ./../ur_bringup:/ros_ws/src/ur_bringup
      - ./../ur5e_onrobot_rg2_moveit_config:/ros_ws/src/ur5e_onrobot_rg2_moveit_config
    command: >
      roslaunch ur_bringup ur5e_bringup.launch 
        robot_ip:=10.15.20.4
        kinematics_config:=/ros_ws/src/ur_bringup/config/ur5e_calibration.yaml
        use_tool_communication:=true


# !TODO
# https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/setup_tool_communication.md
# https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/scripts/tool_communication
# https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/5
# https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/506


# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
# https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/77
# http://axisnj.com/controlling-a-universal-robots-cobot-using-python/
# może to też - https://www.universal-robots.com/articles/ur/programming/secondary-program/
# jakby cos nie dzialalo - https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/master/ur_robot_driver#readme

# https://onrobot.com/sites/default/files/documents/RG2_User%20_Manual_enEN_V1.9.2.pdf

# i zobaczyc te rzeczy w downloads ktore pobrałem wczoraj



# rostopic pub /ur_hardware_interface/script_command std_msgs/String "data: 'rg_grip(10, 40, tool_index=rg_index_get(), blocking=True, depth_compensation=False, popupmsg=True)'"
