services:

  rviz:
    # image: husarion/ur5e:melodic
    build: ./..
    container_name: rviz
    restart: on-failure
    network_mode: host
    ipc: host
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: rosrun rviz rviz -d /ros_ws/src/ur_bringup/config/rviz_config.rviz