services:

  ur-gazebo:
    image: husarion/ur5e:melodic
    container_name: ur-gazebo
    restart: on-failure
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    command: >
      roslaunch ur5e_bringup ur5e_gazebo.launch
        use_rviz:=true