services:

  ur-configuration:
    # image: husarion/ur5e:melodic
    build: ./..
    container_name: ur-configuration
    restart: on-failure
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - ./../ur_bringup:/ros_ws/src/ur_bringup
    command: >
      roslaunch ur_calibration calibration_correction.launch
        robot_ip:=10.42.0.42 
        target_filename:="/ros_ws/src/ur_bringup/config/ur3_calibration.yaml"