controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - panther_ur3_shoulder_pan_joint
      - panther_ur3_shoulder_lift_joint
      - panther_ur3_elbow_joint
      - panther_ur3_wrist_1_joint
      - panther_ur3_wrist_2_joint
      - panther_ur3_wrist_3_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: up